import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import '../models/unit.dart';

class AIService {
  String? apiKey;
  String? model;
  bool _isInitialized = false;

  AIService() {
    _loadEnv();
  }

  Future<void> _loadEnv() async {
    if (_isInitialized) return;

    try {
      await dotenv.load(fileName: ".env");
      apiKey = dotenv.env['GEMINI_API_KEY'];
      model = dotenv.env['GEMINI_MODEL'];
      _isInitialized = true;
    } catch (e) {
      apiKey = '';
      model = 'gemini-2.0-flash-exp';
      _isInitialized = true;
    }
  }

  Future<Unit> generateUnit(String keywords, String level, int numExercises) async {
    await _loadEnv();

    if (apiKey == null || apiKey!.isEmpty) {
      throw Exception('API key not found. Please check your .env file.');
    }

    final modelName = model ?? 'gemini-2.0-flash-exp';

    final prompt = '''
Generate a dictation unit for English learners. The unit should include the following keywords: $keywords.

Requirements:
- Level: $level
- Number of exercises: $numExercises
- Each exercise should be a natural English sentence
- Include hints for each exercise
- Include Japanese translation for each exercise

Output format: JSON with the following structure:
{
  "unit_id": "auto_generated",
  "title": "Generated Unit",
  "level": "$level",
  "description": "AI generated unit for $keywords",
  "exercises": [
    {
      "id": 1,
      "text": "Example sentence",
      "hint": "Hint for the sentence",
      "japanese": "日本語訳",
      "difficulty": "easy/medium/hard"
    }
  ],
  "settings": {
    "voice": "en-US",
    "speed": 1.0,
    "repeat_allowed": 3
  }
}
''';

    final url = 'https://generativelanguage.googleapis.com/v1beta/models/$modelName:generateContent?key=$apiKey';

    final requestBody = jsonEncode({
      'contents': [
        {
          'parts': [
            {'text': prompt}
          ]
        }
      ]
    });

    final response = await http.post(
      Uri.parse(url),
      headers: {'Content-Type': 'application/json'},
      body: requestBody,
    );

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);

      if (data['candidates'] != null && data['candidates'].isNotEmpty) {
        final text = data['candidates'][0]['content']['parts'][0]['text'];

        // Extract JSON from the response, removing markdown code blocks if present
        String cleanedText = text.trim();
        if (cleanedText.startsWith('```json')) {
          cleanedText = cleanedText.substring(7);
        } else if (cleanedText.startsWith('```')) {
          cleanedText = cleanedText.substring(3);
        }
        if (cleanedText.endsWith('```')) {
          cleanedText = cleanedText.substring(0, cleanedText.length - 3);
        }
        cleanedText = cleanedText.trim();

        final jsonStart = cleanedText.indexOf('{');
        final jsonEnd = cleanedText.lastIndexOf('}') + 1;
        if (jsonStart == -1 || jsonEnd == -1) {
          throw Exception('Invalid response format from AI service');
        }

        final jsonStr = cleanedText.substring(jsonStart, jsonEnd);
        final unitJson = jsonDecode(jsonStr);
        unitJson['unit_id'] = 'ai_generated_${DateTime.now().millisecondsSinceEpoch}';
        return Unit.fromJson(unitJson);
      } else {
        throw Exception('No content generated by AI service');
      }
    } else if (response.statusCode == 400) {
      throw Exception('Invalid request. Please check your input.');
    } else if (response.statusCode == 401) {
      throw Exception('API key is invalid or expired.');
    } else if (response.statusCode == 403) {
      throw Exception('API access forbidden. Check your API key permissions.');
    } else if (response.statusCode == 429) {
      throw Exception('API rate limit exceeded. Please try again later.');
    } else if (response.statusCode >= 500) {
      throw Exception('AI service is temporarily unavailable. Please try again later.');
    } else {
      throw Exception('Failed to generate unit (HTTP ${response.statusCode}).');
    }
  }
}