import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import '../models/unit.dart';

class AIService {
  String? apiKey;
  String? model;
  bool _isInitialized = false;

  AIService() {
    // Load from .env asynchronously
    _loadEnv();
  }

  Future<void> _loadEnv() async {
    if (_isInitialized) return;

    try {
      await dotenv.load(fileName: ".env");
      apiKey = dotenv.env['GEMINI_API_KEY'];
      model = dotenv.env['GEMINI_MODEL'];
      _isInitialized = true;
    } catch (e) {
      print('Error loading env: $e');
      apiKey = '';
      model = 'gemini-3-flash';
      _isInitialized = true;
    }
  }

  Future<Unit> generateUnit(String keywords, String level, int numExercises) async {
    // Ensure environment is loaded
    await _loadEnv();

    if (apiKey == null || apiKey!.isEmpty) {
      throw Exception('API key not found. Please check your .env file.');
    }

    final modelName = model ?? 'gemini-3-flash';

    print('DEBUG: Starting AI generation with keywords: $keywords, level: $level, exercises: $numExercises');
    print('DEBUG: Using model: $modelName');
    print('DEBUG: API key length: ${apiKey!.length}');

    final prompt = '''
Generate a dictation unit for English learners. The unit should include the following keywords: $keywords.

Requirements:
- Level: $level
- Number of exercises: $numExercises
- Each exercise should be a natural English sentence
- Include hints for each exercise
- Include Japanese translation for each exercise

Output format: JSON with the following structure:
{
  "unit_id": "auto_generated",
  "title": "Generated Unit",
  "level": "$level",
  "description": "AI generated unit for $keywords",
  "exercises": [
    {
      "id": 1,
      "text": "Example sentence",
      "hint": "Hint for the sentence",
      "japanese": "日本語訳",
      "difficulty": "easy/medium/hard"
    }
  ],
  "settings": {
    "voice": "en-US",
    "speed": 1.0,
    "repeat_allowed": 3
  }
}
''';

    final fullPrompt = '''
Generate a dictation unit for English learners. The unit should include the following keywords: $keywords.

Requirements:
- Level: $level
- Number of exercises: $numExercises
- Each exercise should be a natural English sentence
- Include hints for each exercise
- Include Japanese translation for each exercise

Output format: JSON with the following structure:
$prompt
''';

    final url = 'https://generativelanguage.googleapis.com/v1/models/$modelName:generateContent?key=$apiKey';
    print('DEBUG: API URL: $url');

    final requestBody = jsonEncode({
      'contents': [
        {
          'parts': [
            {'text': fullPrompt}
          ]
        }
      ]
    });
    print('DEBUG: Request body length: ${requestBody.length}');

    final response = await http.post(
      Uri.parse(url),
      headers: {'Content-Type': 'application/json'},
      body: requestBody,
    );

    print('DEBUG: Response status code: ${response.statusCode}');
    print('DEBUG: Response headers: ${response.headers}');
    print('DEBUG: Response body length: ${response.body.length}');
    print('DEBUG: Response body: ${response.body}');

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      print('DEBUG: Full response data: $data');

      if (data['candidates'] != null && data['candidates'].isNotEmpty) {
        final text = data['candidates'][0]['content']['parts'][0]['text'];
        print('DEBUG: Full generated text: $text');

        // Extract JSON from the response
        final jsonStart = text.indexOf('{');
        final jsonEnd = text.lastIndexOf('}') + 1;
        if (jsonStart == -1 || jsonEnd == -1) {
          print('DEBUG: No JSON found in response');
          throw Exception('Invalid response format from AI service');
        }

        final jsonStr = text.substring(jsonStart, jsonEnd);
        print('DEBUG: Extracted JSON: $jsonStr');
        final unitJson = jsonDecode(jsonStr);
        // Generate unique ID for the generated unit
        unitJson['unit_id'] = 'ai_generated_${DateTime.now().millisecondsSinceEpoch}';
        print('DEBUG: Parsed unit JSON: $unitJson');
        return Unit.fromJson(unitJson);
      } else {
        print('DEBUG: No candidates in response');
        throw Exception('No content generated by AI service');
      }
    } else if (response.statusCode == 400) {
      throw Exception('Invalid request. Please check your input.\nResponse: ${response.body}');
    } else if (response.statusCode == 401) {
      throw Exception('API key is invalid or expired.\nResponse: ${response.body}');
    } else if (response.statusCode == 403) {
      throw Exception('API access forbidden. Check your API key permissions.\nResponse: ${response.body}');
    } else if (response.statusCode == 429) {
      throw Exception('API rate limit exceeded. Please try again later.\nResponse: ${response.body}');
    } else if (response.statusCode >= 500) {
      throw Exception('AI service is temporarily unavailable. Please try again later.\nResponse: ${response.body}');
    } else {
      throw Exception('Failed to generate unit (HTTP ${response.statusCode}).\nResponse: ${response.body}');
    }
  }
}